# Generated by Django 5.0.6 on 2024-06-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
